apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        service_name: mysql
    spec:
        strategy:
    {{ toYaml .Values.strategy | indent 4 }}
      containers:
        - name: mysql
          image: image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mysecret
                  key: password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    service_name: mysql