apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
  MEDIAWIKI_DBUSER: YWRtaW4=
  MEDIAWIKI_DBPASSWORD: MWYyZDFlMmU2N2Rm
  
